name = "api-x-gen"
main = "index.js"
compatibility_date = "2024-11-27"
workers_dev = false

[observability]
enabled = true
head_sampling_rate = 1

[[routes]]
pattern = "api-x-gen.fayempire.com"
custom_domain = true
